{{ if eq .chezmoi.os "darwin" }}
[".hammerspoon/stackline"]
    type = "archive"
    url = "https://github.com/AdamWagner/stackline/archive/refs/heads/main.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".hammerspoon/Spoons/FocusHighlight.spoon"]
    type = "archive"
    url = "https://github.com/dtinth/FocusHighlight.spoon/archive/refs/tags/v0.1.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["Library/Keyboard Layouts/ColemakDHm.bundle"]
    type = "archive"
    url = "https://github.com/narze/Colemak-DHm/releases/download/stable/ColemakDHm.bundle.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
["Library/Keyboard Layouts/Manoonchai-ColemakDH-Mod.keylayout"]
    type = "file"
    url = "https://github.com/Manoonchai/Manoonchai/releases/download/v1.0b2/Manoonchai-ColemakDH-Mod.keylayout"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
{{ end -}}

[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf"
    refreshPeriod = "168h"
[".tmux.conf.local"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf.local"
    refreshPeriod = "168h"
