{{ if eq .chezmoi.os "darwin" }}
["Library/Keyboard Layouts/Manoonchai.keylayout"]
    type = "file"
    url = "https://github.com/Manoonchai/Manoonchai/releases/download/v1.0/Manoonchai.keylayout"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
{{ end -}}

[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf"
    refreshPeriod = "168h"
[".tmux.conf.local"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf.local"
    refreshPeriod = "168h"
